name: test

on: push

jobs:
  test:
    name: test
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - uses: baschny/php-composer-action@v1
        with:
          composer_version: 2
          command: install
          args: --optimize-autoloader --no-progress --no-dev

      - run: docker-compose up -d
      - run: docker-compose exec -T php /var/www/html/vendor/bin/phpunit
